- nodeset:
    name: emea-node
    nodes:
      - name: node
        label: ubuntu-bionic      
#- job:
#    name: checklabel
#    run: playbooks/checklabel.yaml
#    parent: location

- job:
    name: printlabel
    run: playbooks/printlabel.yaml
    parent: location
    nodeset: emea-node
 

- project:
    checklabel:
      jobs:
 #      - checklabel
       - printlabel
