- nodeset:
    name: emea-node
    nodes:
      - name: node
        label: ubuntu-bionic
        
- job:
    name: checklabel
    run: playbooks/checklabel.yaml
    parent: location
    vars:
      location_name: "emea-node"
- job:
    name: printlabel
    run: playbooks/printlabel.yaml
    parent: location
 

- project:
    checklabel:
      jobs:
       - checklabel
       - printlabel:
           nodeset: "{{ location_name }}"
