- job:
    name: checklabel
    run: playbooks/checklabel.yaml
    parent: location

- job:
    name: printlabel
    run: playbooks/printlabel.yaml
    parent: location
 

- project:
    checklabel:
      jobs:
       - checklabel
       - printlabel
