- nodeset:
    name: emea-node
    nodes:
      - name: node
        label: ubuntu-bionic
        
- job:
    name: checklabel
    run: playbooks/printlabel.yaml
    parent: location
    vars:
      location_name: "emea-node"

- project:
    checklabel:
      jobs:
       - checklabel:
           nodeset: "{{ (zuul.projects.values() | list | json_query(location_name)) }}"
