- nodeset:
    name: emea-node
    nodes:
      - name: node
        label: ubuntu-bionic
        
- job:
    name: checklabel
    run: playbooks/printlabel.yaml
    parent: location

- project:
    checklabel:
      jobs:
       - checklabel:
           nodeset: emea-node
