- hosts: all
  tasks:
    - name: pull request dependent job
      debug:
        msg: "In Check label emea job"
    - name: change url
      debug:
       msg: "{{ zuul.change_url }}"
#    - name: return zuul location
#      debug:
#       msg: "The zuul location returned is: {{ zuul_return_location }}"
